imports:
  - php
filter:
  paths: [Gears/*]
  excluded_paths: [vendor/*, Tests/*]
before_commands:
  - composer install
tools:
  external_code_coverage: true
  php_code_sniffer: true
  php_cs_fixer: true
  php_mess_detector: true
  php_pdepend: true
  php_analyzer: true
  sensiolabs_security_checker: true
  php_cpd:
    enabled: true
    excluded_dirs: [vendor, Tests]
  php_loc:
    enabled: true
    excluded_dirs: [vendor, Tests]