imports:
  - php
filter:
  paths: [Gears/*]
  excluded_paths: [vendor/*, Tests/*]
before_commands:
  - composer install
tools:
  external_code_coverage: true
  php_code_sniffer:
    enabled: true
    tab_width: 4
    encoding: utf8
    standard: PSR2
  php_cpd:
    enabled: true
    excluded_dirs: [vendor, Tests]
  php_cs_fixer:
    enabled: true
    config:
      level: psr2
  php_mess_detector: 
    enabled: true
  php_pdepend:
    enabled: true
  php_loc:
    enabled: true
    excluded_dirs: [vendor, Tests]
  php_analyzer: true
  sensiolabs_security_checker: true